// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "yandex-gophkeeper-client/internal/auth/entity"

	mock "github.com/stretchr/testify/mock"
)

// Delivery is an autogenerated mock type for the Delivery type
type Delivery struct {
	mock.Mock
}

// Login provides a mock function with given fields: dto
func (_m *Delivery) Login(dto *entity.LoginDto) (string, error) {
	ret := _m.Called(dto)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.LoginDto) (string, error)); ok {
		return rf(dto)
	}
	if rf, ok := ret.Get(0).(func(*entity.LoginDto) string); ok {
		r0 = rf(dto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*entity.LoginDto) error); ok {
		r1 = rf(dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Registration provides a mock function with given fields: dto
func (_m *Delivery) Registration(dto *entity.LoginDto) (string, error) {
	ret := _m.Called(dto)

	if len(ret) == 0 {
		panic("no return value specified for Registration")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.LoginDto) (string, error)); ok {
		return rf(dto)
	}
	if rf, ok := ret.Get(0).(func(*entity.LoginDto) string); ok {
		r0 = rf(dto)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*entity.LoginDto) error); ok {
		r1 = rf(dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDelivery creates a new instance of Delivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Delivery {
	mock := &Delivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
